version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - .:/app
      - uploads:/app/uploads
    restart: unless-stopped
    env_file:
      - .env

volumes:
  uploads:
