version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - ALWAYS_ADMIN=${ALWAYS_ADMIN}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    volumes:
      - .:/app
      - uploads:/app/uploads
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres_data:
  uploads:

networks:
  app_network:
